name: onssetmg_env
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20220623.0
  - access=1.1.8
  - affine=2.4.0
  - alphashape=1.3.1
  - amply=0.1.6
  - anyio=4.3.0
  - aom=3.5.0
  - appdirs=1.4.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - arrow-cpp=6.0.2
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attrs=23.2.0
  - aws-c-cal=0.5.11
  - aws-c-common=0.6.2
  - aws-c-event-stream=0.2.7
  - aws-c-io=0.10.5
  - aws-checksums=0.1.11
  - aws-requests-auth=0.4.3
  - aws-sdk-cpp=1.8.186
  - babel=2.14.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=2.0.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=6.1.0
  - blinker=1.7.0
  - blosc=1.21.5
  - boost-cpp=1.84.0
  - boto3=1.34.79
  - botocore=1.34.79
  - branca=0.7.1
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - brotlipy=0.7.0
  - bs4=4.12.3
  - bzip2=1.0.8
  - c-ares=1.28.1
  - c-blosc2=2.14.3
  - ca-certificates=2024.2.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - certifi=2024.2.2
  - cffi=1.16.0
  - cfitsio=4.2.0
  - chardet=5.2.0
  - charls=2.4.2
  - charset-normalizer=3.3.2
  - click=8.1.7
  - click-log=0.4.0
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - comm=0.2.2
  - contextily=1.6.0
  - contourpy=1.1.1
  - cryptography=39.0.0
  - curl=8.1.2
  - cycler=0.12.1
  - cython=3.0.10
  - cytoolz=0.12.3
  - dask-core=2023.5.0
  - dataclasses=0.8
  - dav1d=1.2.1
  - debugpy=1.8.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - deprecated=1.2.14
  - deprecation=2.1.0
  - descartes=1.1.0
  - dnspython=2.6.1
  - docopt=0.6.2
  - docutils=0.20.1
  - earthpy=0.9.4
  - entrypoints=0.4
  - esda=2.5.1
  - et_xmlfile=1.1.0
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.6.2
  - fiona=1.9.1
  - flask=3.0.2
  - flask_cors=3.0.10
  - flask_json=0.3.4
  - folium=0.16.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.51.0
  - fqdn=1.5.1
  - freetype=2.12.1
  - freexl=1.0.6
  - fsspec=2024.3.1
  - geographiclib=2.0
  - geojson=3.1.0
  - geopandas=0.13.2
  - geopandas-base=0.13.2
  - geopy=2.4.1
  - geos=3.11.1
  - geotiff=1.7.1
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gflags=2.2.2
  - giddy=2.3.5
  - giflib=5.2.1
  - glib=2.78.1
  - glib-tools=2.78.1
  - glog=0.6.0
  - glpk=5.0
  - grpc-cpp=1.45.2
  - gst-plugins-base=1.21.3
  - gstreamer=1.21.3
  - h11=0.14.0
  - h2=4.1.0
  - h3-py=3.7.7
  - hdbscan=0.8.33
  - hdf4=4.2.15
  - hdf5=1.12.2
  - hpack=4.0.0
  - httpcore=1.0.5
  - httpx=0.27.0
  - hyperframe=6.0.1
  - icc_rt=2022.1.0
  - icu=70.1
  - idna=3.6
  - imagecodecs=2023.1.23
  - imageio=2.34.0
  - importlib-metadata=7.1.0
  - importlib-resources=6.4.0
  - importlib_metadata=7.1.0
  - importlib_resources=6.4.0
  - importnb=2023.11.1
  - inequality=1.0.0
  - intel-openmp=2023.2.0
  - ipykernel=6.29.3
  - ipython=8.12.2
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.2
  - isoduration=20.11.0
  - itsdangerous=2.1.2
  - jdcal=1.4.1
  - jedi=0.19.1
  - jinja2=3.1.3
  - jmespath=1.0.1
  - joblib=1.3.2
  - jpeg=9e
  - json5=0.9.24
  - jsonlines=1.2.0
  - jsonpointer=2.4
  - jsonschema=4.21.1
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.21.1
  - jupyter=1.0.0
  - jupyter-lsp=2.2.4
  - jupyter_client=8.6.1
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.13.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.1.5
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.25.4
  - jupyterlab_widgets=3.0.10
  - jxrlib=1.1
  - kealib=1.5.0
  - kiwisolver=1.4.5
  - krb5=1.20.1
  - lazy_loader=0.4
  - lcms2=2.15
  - lerc=4.0.0
  - libabseil-static=20220623.0
  - libaec=1.1.3
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libavif=0.11.1
  - libblas=3.9.0
  - libboost=1.84.0
  - libboost-devel=1.84.0
  - libboost-headers=1.84.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcurl=8.1.2
  - libdeflate=1.17
  - libevent=2.1.10
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgdal=3.6.2
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libglib=2.78.1
  - libhwloc=2.9.3
  - libiconv=1.17
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libogg=1.3.4
  - libpng=1.6.43
  - libpq=15.1
  - libprotobuf=3.20.3
  - libpysal=4.8.0
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libsqlite=3.45.2
  - libssh2=1.10.0
  - libthrift=0.16.0
  - libtiff=4.5.0
  - libutf8proc=2.8.0
  - libvorbis=1.3.7
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.13
  - libxml2=2.12.6
  - libxslt=1.1.39
  - libzip=1.9.2
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - llvmlite=0.41.1
  - locket=1.0.0
  - lxml=5.1.0
  - lz4-c=1.9.4
  - m2w64-expat=2.1.1
  - m2w64-gcc-libgfortran
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gettext=0.19.7
  - m2w64-gmp=6.1.0
  - m2w64-libiconv=1.14
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-xz=5.2.2
  - mapclassify=2.5.0
  - markupsafe=2.1.5
  - matplotlib=3.7.3
  - matplotlib-base=3.7.3
  - matplotlib-inline=0.1.6
  - mercantile=1.2.1
  - mgwr=2.2.1
  - mistune=3.0.2
  - mkl=2023.2.0
  - mkl-service=2.4.1
  - mkl_fft=1.3.8
  - mkl_random=1.2.5
  - momepy=0.6.0
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - munch=4.0.0
  - munkres=1.1.4
  - nbclient=0.10.0
  - nbconvert=7.16.3
  - nbconvert-core=7.16.3
  - nbconvert-pandoc=7.16.3
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - networkx=3.1
  - notebook=7.1.2
  - notebook-shim=0.2.4
  - numba=0.58.1
  - numpy=1.24.3
  - numpy-base=1.24.3
  - olefile=0.47
  - openjpeg=2.5.0
  - openpyxl=3.1.2
  - openssl=1.1.1w
  - overrides=7.7.0
  - packaging=24.0
  - palettable=3.3.3
  - pandas=2.0.3
  - pandoc=3.1.13
  - pandocfilters=1.5.0
  - parquet-cpp=1.5.1
  - parso=0.8.4
  - partd=1.4.1
  - patsy=0.5.6
  - pcre=8.45
  - pcre2=10.40
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=24.0
  - pixman=0.43.4
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.0
  - ply=3.11
  - pointpats=2.4.0
  - pooch=1.8.1
  - poppler=22.12.0
  - poppler-data=0.4.12
  - postgresql=15.1
  - proj=9.1.1
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.42
  - prompt_toolkit=3.0.42
  - psutil=5.9.8
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pulp=2.8.0
  - pure_eval=0.2.2
  - pyarrow=6.0.2
  - pycparser=2.22
  - pydap=3.4.0
  - pygments=2.17.2
  - pynndescent=0.5.12
  - pyopenssl=23.2.0
  - pyparsing=3.1.2
  - pyproj=3.5.0
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.20.0
  - pysal=23.7
  - pysocks=1.7.1
  - python=3.8.15
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.19.1
  - python-json-logger=2.0.7
  - python-tzdata=2024.1
  - python_abi
  - pytz=2024.1
  - pywavelets=1.4.1
  - pywin32=306
  - pywinpty=2.0.13
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qt=5.15.6
  - qt-main=5.15.6
  - qt-webengine=5.15.4
  - qtconsole=5.5.1
  - qtconsole-base=5.5.1
  - qtpy=2.4.1
  - quantecon=0.7.2
  - quilt3=5.4.0
  - rasterio=1.3.6
  - rasterstats=0.19.0
  - re2=2022.06.01
  - referencing=0.34.0
  - requests=2.31.0
  - requests-futures=1.0.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.18.0
  - rtree=1.2.0
  - s3transfer=0.10.1
  - scikit-image=0.21.0
  - scikit-learn=1.3.2
  - scipy=1.10.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - segregation=2.5
  - send2trash=1.8.2
  - setuptools=69.2.0
  - shapely=2.0.1
  - simplejson=3.19.2
  - sip=6.7.12
  - six=1.16.0
  - snappy
  - sniffio=1.3.1
  - snuggs=1.4.7
  - soupsieve=2.5
  - spaghetti=1.7.5.post1
  - spglm=1.1.0
  - spint=1.0.7
  - splot=1.1.5.post1
  - spopt=0.5.0
  - spreg=1.4.2
  - spvcm=0.3.0
  - sqlite=3.45.2
  - stack_data=0.6.2
  - statsmodels=0.14.1
  - sympy=1.12
  - tbb=2021.11.0
  - tenacity=8.2.3
  - terminado=0.18.1
  - testpath=0.6.0
  - threadpoolctl=3.4.0
  - tifffile=2023.7.10
  - tiledb=2.13.2
  - tinycss2=1.2.1
  - tk=8.6.13
  - tobler=0.11.2
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.1
  - tornado=6.4
  - tqdm=4.66.2
  - traitlets=5.14.2
  - trimesh=4.2.4
  - types-python-dateutil=2.9.0.20240316
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - typing_utils=0.1.0
  - ucrt=10.0.22621.0
  - umap-learn=0.5.5
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - uriparser=0.9.7
  - urllib3=1.26.18
  - vc=14.3
  - vc14_runtime=14.38.33130
  - vs2015_runtime=14.38.33130
  - wcwidth=0.2.13
  - webcolors=1.13
  - webencodings=0.5.1
  - webob=1.8.7
  - websocket-client=1.7.0
  - werkzeug=3.0.2
  - wheel=0.43.0
  - widgetsnbextension=4.0.10
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - wrapt=1.16.0
  - xarray=2022.11.0
  - xerces-c=3.2.5
  - xlrd=2.0.1
  - xlsxwriter=3.1.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xyzservices=2024.4.0
  - xz=5.2.6
  - yaml=0.2.5
  - yellowbrick=1.5
  - zeromq=4.3.5
  - zfp=1.0.1
  - zipp=3.17.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.5
  - pip:
      - distancerasters==0.3.2
      - gdal==3.0.4